[package]
name = "zeroconf-service-example"
version = "0.1.0"
authors = ["Walker Crouse <walkercrouse@hotmail.com>"]
edition = "2018"

[dependencies]
zeroconf = { path = "../../zeroconf" }
env_logger = "0.10.0"
log = "0.4.20"
