name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        run: ./scripts/checkfmt.sh
      - name: Build
        run: ./scripts/buildall.sh
      - name: Run tests
        run: cargo test --verbose

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: "sudo apt -y install avahi-daemon libavahi-client-dev && sudo systemctl start avahi-daemon.service"
      - name: Check formatting
        run: ./scripts/checkfmt.sh
      - name: Build
        run: ./scripts/buildall.sh
      - name: Run tests
        run: cargo test --verbose
